def create_domain(domain_number):
    print("qa;subscribermgmt;domain")
    print("add mtlasdev%s.net" % domain_number) 

def create_service_provider(sp_name, domain_number):
    print("qa;subscribermgmt;serviceprovider;")
    print("add %s false false mtlasdev%s.net;" % (sp_name, domain_number) )
    print("qa;subscribermgmt;serviceprovider;groupservices")
    print("set %s \"Account/Authorization Codes\" true true" % sp_name)
    print("set %s \"Auto Attendant\" true true" % sp_name)
    print("set %s \"Auto Attendant - Video\" true true" % sp_name)
    print("set %s \"Call Capacity Management\" true true" % sp_name)
    print("set %s \"Call Park\" true true" % sp_name)
    print("set %s \"Call Pickup\" true true" % sp_name)
    print("set %s \"Custom Ringback Group\" true true" % sp_name)    
    print("set %s \"Custom Ringback Group - Video\" true true" % sp_name)
    print("set %s \"Enhanced Outgoing Calling Plan\" true true" % sp_name)
    print("set %s \"Hunt Group\" true true" % sp_name)
    print("set %s \"Incoming Calling Plan\" true true" % sp_name)
    print("set %s \"Intercept Group\" true true" % sp_name)
    print("set %s \"LDAP Integration\" true true" % sp_name)
    print("set %s \"Music On Hold\" true true" % sp_name)
    print("set %s \"Music On Hold - Video\" true true" % sp_name)
    print("set %s \"Outgoing Calling Plan\" true true" % sp_name)
    print("set %s \"Preferred Carrier Group\" true true" % sp_name)
    print("set %s \"Voice Messaging Group\" true true" % sp_name)
    
    print("qa;subscribermgmt;serviceprovider;userservices")
    print("set %s \"Advice Of Charge\" true true" % sp_name)
    print("set %s \"Alternate Numbers\" true true" % sp_name)
    print("set %s \"Anonymous Call Rejection\" true true" % sp_name)
    print("set %s \"Automatic Callback\" true true" % sp_name)
    print("set %s \"Barge-in Exempt\" true true" % sp_name)
    print("set %s \"BroadWorks Anywhere\" true true" % sp_name)
    print("set %s \"Call Forwarding Always\" true true" % sp_name)
    print("set %s \"Call Forwarding Busy\" true true" % sp_name)
    print("set %s \"Call Forwarding No Answer\" true true" % sp_name)
    print("set %s \"Call Forwarding Not Reachable\" true true" % sp_name)
    print("set %s \"Call Forwarding Selective\" true true" % sp_name)
    print("set %s \"Calling Line ID Blocking Override\" true true" % sp_name)
    print("set %s \"Calling Line ID Delivery Blocking\" true true" % sp_name)
    print("set %s \"Call Notify\" true true" % sp_name)
    print("set %s \"Call Return\" true true" % sp_name)
    print("set %s \"Call Transfer\" true true" % sp_name)
    print("set %s \"Call Waiting\" true true" % sp_name)
    print("set %s \"Charge Number\" true true" % sp_name)
    print("set %s \"Client Call Control\" true true" % sp_name)
    print("set %s \"CommPilot Call Manager\" true true" % sp_name)
    print("set %s \"Communication Barring User-Control\" true true" % sp_name)
    print("set %s \"Connected Line Identification Presentation\" true true" % sp_name)
    print("set %s \"Connected Line Identification Restriction\" true true" % sp_name)
    print("set %s \"Customer Originated Trace\" true true" % sp_name)
    print("set %s \"Custom Ringback User\" true true" % sp_name)
    print("set %s \"Custom Ringback User - Call Waiting\" true true" % sp_name)
    print("set %s \"Custom Ringback User - Video\" true true" % sp_name)
    print("set %s \"Directed Call Pickup\" true true" % sp_name)
    print("set %s \"Directed Call Pickup with Barge-in\" true true" % sp_name)
    print("set %s \"Directory Number Hunting\" true true" % sp_name)
    print("set %s \"Diversion Inhibitor\" true true" % sp_name)
    print("set %s \"Do Not Disturb\" true true" % sp_name)
    print("set %s \"Enhanced Call Logs\" true true" % sp_name)
    print("set %s \"External Calling Line ID Delivery\" true true" % sp_name)
    print("set %s \"External Custom Ringback\" true true" % sp_name)
    print("set %s \"Fax Messaging\" true true" % sp_name)
    print("set %s \"Intercept User\" true true" % sp_name)
    print("set %s \"Internal Calling Line ID Delivery\" true true" % sp_name)
    print("set %s \"Last Number Redial\" true true" % sp_name)
    print("set %s \"Malicious Call Trace\" true true" % sp_name)
    print("set %s \"Multiple Call Arrangement\" true true" % sp_name)
    print("set %s \"Music On Hold User\" true true" % sp_name)
    print("set %s \"MWI Delivery to Mobile Endpoint\" true true" % sp_name)
    print("set %s \"N-Way Call\" true true" % sp_name)
    print("set %s \"Outlook Integration\" true true" % sp_name)
    print("set %s \"Physical Location\" true true" % sp_name)
    print("set %s \"Preferred Carrier User\" true true" % sp_name)
    print("set %s \"Prepaid\" true true" % sp_name)
    print("set %s \"Priority Alert\" true true" % sp_name)
    print("set %s \"Privacy\" true true" % sp_name)
    print("set %s \"Selective Call Acceptance\" true true" % sp_name)
    print("set %s \"Selective Call Rejection\" true true" % sp_name)
    print("set %s \"Sequential Ring\" true true" % sp_name)
    print("set %s \"Shared Call Appearance\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 10\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 15\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 20\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 25\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 30\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 35\" true true" % sp_name)
    print("set %s \"Shared Call Appearance 5\" true true" % sp_name)
    print("set %s \"Simultaneous Ring Family\" true true" % sp_name)
    print("set %s \"Simultaneous Ring Personal\" true true" % sp_name)
    print("set %s \"Speed Dial 100\" true true" % sp_name)
    print("set %s \"Speed Dial 8\" true true" % sp_name)
    print("set %s \"Third-Party Voice Mail Support\" true true" % sp_name)
    print("set %s \"Three-Way Call\" true true" % sp_name)
    print("set %s \"Video On Hold User\" true true" % sp_name)
    print("set %s \"Voice Messaging User\" true true" % sp_name)
    print("set %s \"Voice Messaging User - Video\" true true" % sp_name)
    print("set %s \"Voice Portal Calling\" true true" % sp_name)
    
def create_service_pack(sp_name):
    print("qa;SubscriberMgmt;ServiceProvider;ServicePacks")
    print("add %s newPack \"N-Way Call\" true enablePack true" % sp_name)
    print("addService %s newPack \"Call Waiting\"" % sp_name)
    print("addService %s newPack \"Voice Portal Calling\"" % sp_name)
    print("addService %s newPack \"Three-Way Call\"" % sp_name)

def create_groups(group_count, user_count, sp_name, domain_number):
    print("qa;subscribermgmt;group;")
    for i in range(1, group_count + 1):
        print("add %s Group%d  mtlasdev%s.net %d" % (sp_name, 
            i, domain_number, user_count) )
    for j in range(1, group_count + 1):
        print("qa;subscribermgmt;group;userservices;authorize")
        print("set %s Group%d service \"Call Waiting\" true true" % (sp_name,j))
        print("set %s Group%d service \"N-Way Call\" true true" % (sp_name, j))
        print("set %s Group%d service \"Three-Way Call\" true true" % (sp_name, j))
        print("set %s Group%d service \"Voice Portal Calling\" true true" % (sp_name, j))
    
    print("qa; subscribermgmt;group;device")
    for k in range(1, group_count + 1):
        print("add %s Group%d  PolycomPhoneNorth$j \"Polycom Soundpoint IP 600\"" 
            % (sp_name, k))

def create_users(group_count, user_count, sp_name, domain_number):
    for g in range(1, group_count + 1):
        for u in range(1, user_count + 1):
            print("qa;subscribermgmt;user")
            print("add %s Group%d Group%d-User%d@mtlasdev%s.net north john%d north john%d" %
                (sp_name, g, g, u, domain_number, u, u) )              
            print("mtllab")  
            print("mtllab")  
        
        # authorize group service pack    
        print("qa;subscribermgmt;group;userservices;Authorize")
        print("set %s Group%d servicePack newPack true true" % (sp_name, g))
         
        # user service packs
        print("qa;SubscriberMgmt;Group;UserServices;ExistingUser")
        print("add %s Group%d servicePackName newPack" % (sp_name, g))